services:
  postgres:
    image: postgres:15
    container_name: go_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_go:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_go:
    name: postgres_data_go_unique